<a href="https://colab.research.google.com/github/mehrnaz1368/classification/blob/main/Reggression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import numpy as np
data = pd.read_csv('house price.csv')
print(data.head())

  Area  Room  Parking  Warehouse  Elevator         Address         Price  \
0   63     1     True       True      True         Shahran  1.850000e+09   
1   60     1     True       True      True         Shahran  1.850000e+09   
2   79     2     True       True      True          Pardis  5.500000e+08   
3   95     2     True       True      True   Shahrake Qods  9.025000e+08   
4  123     2     True       True      True  Shahrake Gharb  7.000000e+09   

   Price(USD)  
0    61666.67  
1    61666.67  
2    18333.33  
3    30083.33  
4   233333.33  


#Convert categorical data to numerical with LabelEncoder

In [20]:
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()
label = le.fit_transform(data['Parking'])
label

array([1, 1, 1, ..., 0, 1, 0])

In [ ]:
data.drop("Parking", axis=1, inplace=True)
data["Parking"] = label
data

In [22]:
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()
label1 = le.fit_transform(data['Elevator'])
label1

array([1, 1, 1, ..., 0, 1, 1])

In [ ]:
data.drop("Elevator", axis=1, inplace=True)
data["Elevator"] = label1
data

In [24]:
label2 = le.fit_transform(data['Warehouse'])
label2

array([1, 1, 1, ..., 0, 1, 1])

In [ ]:
data.drop("Warehouse", axis=1, inplace=True)
data["Warehouse"] = label2
data

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
label_encoder.fit(data["Address"])

In [ ]:
print(list(label_encoder.classes_))
print()

In [11]:
print(label_encoder.transform(data["Address"]))

[156 156 117 ... 115  39 115]


In [ ]:
label3=label_encoder.transform(data["Address"])
data.drop("Address", axis=1, inplace=True)
data["Address"] = label3
data

In [30]:
print(data.head())

  Area  Room         Price  Price(USD)  Parking  Elevator  Warehouse  Address
0   63     1  1.850000e+09    61666.67        1         1          1      156
1   60     1  1.850000e+09    61666.67        1         1          1      156
2   79     2  5.500000e+08    18333.33        1         1          1      117
3   95     2  9.025000e+08    30083.33        1         1          1      152
4  123     2  7.000000e+09   233333.33        1         1          1      150


In [45]:
print(data.isnull().sum())

Area          0
Room          0
Price         0
Price(USD)    0
Parking       0
Elevator      0
Warehouse     0
Address       0
dtype: int64


#Plot Price with other values

In [33]:
import matplotlib.pyplot as plt
import pylab as pl

In [ ]:
plt.scatter(data.Address, data.Price, color='blue')
plt.xlabel("Address")
plt.ylabel("Price")

In [ ]:
plt.scatter(data.Area, data.Price, color='green')
plt.xlabel("Area")
plt.ylabel("Price")

In [ ]:
plt.scatter(data.Room, data.Price, color='green')
plt.xlabel("Room")
plt.ylabel("Price")

In [ ]:
plt.scatter(data.Parking, data.Price, color='green')
plt.xlabel("Parking")
plt.ylabel("Price")

In [ ]:
plt.scatter(data.Elevator, data.Price, color='red')
plt.xlabel("Elevator")
plt.ylabel("Price")

In [ ]:
plt.scatter(data.Warehouse, data.Price, color='green')
plt.xlabel("Warehouse")
plt.ylabel("Price")

#Creating train and test

In [41]:
msk = np.random.rand(len(data))<0.8
train= data[msk]
test=data[~msk]

In [48]:
my_str = '1,2.345%'

my_float = float(my_str.replace(',', '').replace('%', ''))

print(my_float)  # 👉️ 12.345



12.345


In [49]:
from sklearn import linear_model
regr= linear_model.LinearRegression()
x = np.asanyarray(train[['Address', 'Area', 'Room', 'Parking', 'Elevator', 'Warehouse']])
y = np.asanyarray(train[['Price']])
regr.fit(x, y)
print('Coefficients: ', regr.coef_)

ValueError: ignored